// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoCHeadHome.h"
#include "DriveCmd.h"
#include "ForkOpenFully.h"
#include "ElevToBottom.h"

AutoCHeadHome::AutoCHeadHome() {
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.

	// To run multiple commands at the same time,
	// use AddParallel()
	// e.g. AddParallel(new Command1());
	//      AddSequential(new Command2());
	// Command1 and Command2 will run in parallel.

	// A command group will require all of the subsystems that each member
	// would require.
	// e.g. if Command1 requires chassis, and Command2 requires arm,
	// a CommandGroup containing them would require both the chassis and the
	// arm.
	AddSequential(new DriveCmd(0, 7, -0.55, 93));			// Drive reverse at 0.55 speed for 93 inches
	AddSequential(new ElevToBottom());						// close fork on object
	AddParallel(new ForkOpenFully());						// close fork on object
	AddSequential(new DriveCmd(0, 7, -0.35, 3));			// Drive reverse at 0.25 speed for 87 inches
}
