// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ElevByJoystick.h"

ElevByJoystick::ElevByJoystick() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elev);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void ElevByJoystick::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ElevByJoystick::Execute() {
	Robot::elev->joystickDrive(Robot::oi->getForkJoystick());
	Robot::elev->log(Robot::oi->getForkJoystick());
}

// Make this return true when this Command no longer needs to run execute()
bool ElevByJoystick::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void ElevByJoystick::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ElevByJoystick::Interrupted() {

}
