// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ElevToBottom.h"
#include "../Robot.h"

ElevToBottom::ElevToBottom() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elev);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void ElevToBottom::Initialize() {
	SetTimeout(8);				// If does not reach destination in time then stop
}

// Called repeatedly when this Command is scheduled to run
void ElevToBottom::Execute() {
	Robot::elev->lower();		// Start Motor Moving in
}

// Make this return true when this Command no longer needs to run execute()
bool ElevToBottom::IsFinished() {
	if (IsTimedOut())
		return true;

	if ((Robot::elev->getBottomLmtSw() == Robot::elev->kLmtSwPressed) ||
		(Robot::elev->getHitLmtSw()  ==  Robot::elev->kLmtSwNotPressed))
			return true;

	return false;
}


// Called once after isFinished returns true
void ElevToBottom::End() {
	Robot::elev->stop();		// Stop Motor Moving
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ElevToBottom::Interrupted() {
	End();
}
