// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ForkOpen.h"
#include "../Robot.h"

ForkOpen::ForkOpen(float timeout) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	this->timeout = timeout;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::fork);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void ForkOpen::Initialize() {
	SetTimeout(timeout);				// If does not reach destination in time then stop
}

// Called repeatedly when this Command is scheduled to run
void ForkOpen::Execute() {
	Robot::fork->open();		// Start Motor Moving in
}

// Make this return true when this Command no longer needs to run execute()
bool ForkOpen::IsFinished() {
	if (IsTimedOut() || (Robot::fork->getOutsideLmtSw() == Robot::fork->kLmtSwPressed))
		return true;
	else
		return false;
}

// Called once after isFinished returns true
void ForkOpen::End() {
	Robot::fork->stop();		// Stop the Motor now !
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ForkOpen::Interrupted() {
	End();
}
