// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoAGrabandLiftTote.h"
#include "Commands/AutoBGrabandLiftCan.h"
#include "Commands/AutoCHeadHome.h"
#include "Commands/AutoDGet1Tote.h"
#include "Commands/AutoEGetCan.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveByJoystick.h"
#include "Commands/DriveCmd.h"
#include "Commands/DriveResetEncoders.h"
#include "Commands/DriveResetGyro.h"
#include "Commands/DriveToContact.h"
#include "Commands/ElevByJoystick.h"
#include "Commands/ElevHold.h"
#include "Commands/ElevRaise.h"
#include "Commands/ElevRaiseToPosition.h"
#include "Commands/ElevToBottom.h"
#include "Commands/ForkByJoystick.h"
#include "Commands/ForkClose.h"
#include "Commands/ForkCtrAndGrab.h"
#include "Commands/ForkOpen.h"
#include "Commands/ForkOpenFully.h"
#include "Commands/WaitTime.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	forkJoystick = new Joystick(1);
	
	forkCloseAndAlign = new JoystickButton(forkJoystick, 1);
	forkCloseAndAlign->WhileHeld(new ForkCtrAndGrab());
	forkCloseBtn = new JoystickButton(forkJoystick, 6);
	forkCloseBtn->WhenPressed(new ForkClose());
	forkOpenBtn = new JoystickButton(forkJoystick, 2);
	forkOpenBtn->WhenPressed(new ForkOpenFully());
	driveJoystick = new Joystick(0);
	
     

        // SmartDashboard Buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getForkJoystick() {
	return forkJoystick;
}

Joystick* OI::getDriveJoystick() {
	return driveJoystick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
