// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	float kElevPosB = 15;	// Transport Height

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SpeedController* drivetrainLFSpeedCtrlr;
	static SpeedController* drivetrainFRSpeedCtrlr;
	static SpeedController* drivetrainRLSpeedCtrlr;
	static SpeedController* drivetrainRRSpeedCtrlr;
	static RobotDrive* drivetrainRobotDrive;
	static Encoder* drivetrainLFQuadratureEncoder;
	static Encoder* drivetrainRFQuadratureEncoder;
	static Gyro* drivetrainGyro;
	static DigitalInput* drivetrainContactLmtSw;
	static SpeedController* forkMotor;
	static DigitalInput* forkOutsideLmtSw;
	static DigitalInput* forkInsideLmtSw;
	static DigitalInput* forkContactLeft;
	static DigitalInput* forkContactRight;
	static SpeedController* elevMotor;
	static DigitalInput* elevTopLmtSw;
	static DigitalInput* elevBottomLmtSw;
	static DigitalInput* elevHitLmtSw;
	static Encoder* elevEncoder;
	static Relay* elevBrake;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
